# Site settings
title: Chen Gao
description: 'My Personal Website'
baseurl: ''
profilepic: '/images/chen_gao.jpeg'
bkimage: '/images/bk1.jpeg'
google_analytics: UA-XXXXXX-X
font_awesome: '53d7a3a62b.js'

author:
  name: 'Chen Gao'
  email: 'ukieg555@gmail.com'
  github_username:  'ukie555'

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
